### ISSUE TITLE
In another screen, the position is wrong

### ISSUE THREAD

**Issue by sxzxs** [iseahound/TextRender#11] opened 2022-08-15 03:37 UTC
I have double screen, but in another screen, the position may wrong!

**Comment by iseahound** [comment] 2022-08-15 04:20
Can you show where it is wrong? This was tested using Mutiple monitors with different DPI.

You may find a test script in: https://github.com/iseahound/TextRender/releases/tag/v1.8 called Showcase 03 - Speed Test

**Comment by sxzxs** [comment] 2022-08-15 04:59
> 

![image](https://user-images.githubusercontent.com/26515268/184578863-2180821a-a95e-40ad-9b12-b468173bda58.png)
![image](https://user-images.githubusercontent.com/26515268/184578891-1ceea85a-6a26-4a5f-9949-9c53c3402d03.png)
![image](https://user-images.githubusercontent.com/26515268/184578990-471de841-743a-45bf-aaf1-1a1f21e004ef.png)
![image](https://user-images.githubusercontent.com/26515268/184579079-5df954cc-371e-4323-a1b9-e9b9732d7671.png)
![image](https://user-images.githubusercontent.com/26515268/184579113-ce8a8813-1329-4f6d-9451-4e911ce92bf1.png)

**Comment by sxzxs** [comment] 2022-08-17 06:05
this is a bug? i run same test with v2, same result.

**Comment by iseahound** [comment] 2022-08-18 22:53
Yes, this does appear to be a bug. It seems to only happen with the y-axis on multi monitor systems

**Comment by iseahound** [comment] 2022-08-18 23:25
And the reason it happens is because of lazy coding :)

![image](https://user-images.githubusercontent.com/9779668/185512064-c5bd6e6e-842d-41db-97c3-d391331bcf25.png)

I should have used a proper struct.

**Comment by iseahound** [comment] 2022-08-18 23:54
Fixed by b734c91de0239d463e89d2c3c7d3bbab8894c89f. 

Thank you for providing detailed instructions on how to reproduce the error, and for being patient. 

Please test the v1 and v2 code to ensure it is fixed

**Comment by sxzxs** [comment] 2022-08-19 02:50
> 

I have test with v2 and v1 use new version,it work good!
Thans you very much! I often use TestRender!

I have a quick question, can I know the height or width of the text before rendering?

**Comment by iseahound** [comment] 2022-08-19 03:47
I suppose you could do something like this:

    #include TextRender.ahk
    wh := Width_and_Height("hello world!", "s:42")
    MsgBox wh[1] ", " wh[2]

    Width_and_Height(text, s1:="", s2:="") {
        static tr := TextRender()
        tr.Draw(text, "x:0 y:0 c:None" . s1, s2) ; only supports string syntax, feel free to check for an object!
        try return [tr.w, tr.h]
        finally tr.Flush() ; Use this to clear the graphics 
    }

**Closed by iseahound** 2022-08-19 03:47 UTC
